# Generated by Django 4.0.6 on 2022-08-22 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocrTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='data published...')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('place', models.CharField(max_length=30)),
                ('ranking', models.CharField(max_length=10)),
                ('pub_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrTest.rankpost')),
            ],
        ),
    ]
