# Generated by Django 4.0.6 on 2022-08-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrTest', '0002_rankpost_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rank'),
        ),
    ]
