# Generated by Django 4.0.6 on 2022-08-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=16, primary_key=True, serialize=False)),
                ('pw', models.CharField(db_column='PW', max_length=20)),
                ('date', models.DateTimeField(db_column='DATE')),
                ('permit', models.PositiveIntegerField(blank=True, db_column='PERMIT', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('number', models.AutoField(db_column='NUMBER', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='TITLE', max_length=150)),
                ('content', models.TextField(db_column='CONTENT')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('id', models.CharField(db_column='ID', max_length=20)),
                ('password', models.CharField(db_column='PASSWORD', max_length=20)),
                ('pub_date', models.DateTimeField(db_column='DATE')),
                ('hit', models.PositiveIntegerField(db_column='HIT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.member')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('number', models.AutoField(db_column='NUMBER', primary_key=True, serialize=False)),
                ('board_number', models.PositiveIntegerField(db_column='BOARD_NUMBER')),
                ('id', models.CharField(db_column='ID', max_length=20)),
                ('content', models.TextField(db_column='CONTENT')),
                ('date', models.DateTimeField(db_column='DATE')),
                ('parent_number', models.ForeignKey(db_column='PARENT_NUMBER', on_delete=django.db.models.deletion.CASCADE, to='mysite.post')),
            ],
        ),
    ]
