# Generated by Django 4.0.6 on 2022-08-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0002_remove_photo_post_remove_post_user_delete_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('rep_date', models.DateTimeField()),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.board')),
            ],
        ),
    ]
