# Generated by Django 4.0.6 on 2022-08-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
